import streamlit as st
import pandas as pd
import folium
from streamlit_folium import st_folium

# 1. Configuración de página
st.set_page_config(page_title="C5 - Registro Maestro", layout="wide")

# 2. Inicializar estados
if "autenticado" not in st.session_state: st.session_state.autenticado = False
if 'lat_f' not in st.session_state: st.session_state.lat_f = ""
if 'lon_f' not in st.session_state: st.session_state.lon_f = ""

def pantalla_login():
    st.title("🔐 CENTRO DE OPERACION NACIONAL - C5")
    user = st.text_input("Usuario")
    password = st.text_input("Contraseña", type="password")
    if st.button("Iniciar Sesión"):
        usuarios_permitidos = {"CONC5": "12345", "ELMER RODRIGUEZ": "ELIZAharol31"}
        if user in usuarios_permitidos and usuarios_permitidos[user] == password:
            st.session_state.autenticado = True
            st.rerun()
        else:
            st.error("Usuario o contraseña incorrectos")

if not st.session_state.autenticado:
    pantalla_login()
else:
    st.title("🛡️ REGISTROS POSITIVOS DEL C.O.N - C5")
    
    # --- REEMPLAZA TU BLOQUE DE MAPA ACTUAL POR ESTE ---

    # Usamos la capa de ESRI World Imagery (Satelital)
    m = folium.Map(
    location=[8.9824, -79.5199], 
    zoom_start=15, 
    tiles="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
    attr="Esri"
    )

    # Esto agrega las etiquetas (nombres de calles y lugares) sobre la imagen satelital
    folium.TileLayer(
    tiles="https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}",
    attr="Esri",
    name="Labels",
    overlay=True
    ).add_to(m)

    m.add_child(folium.LatLngPopup())
    map_data = st_folium(m, height=800, width=1800)

    # Lógica de captura inmediata
    if map_data and map_data.get('last_clicked'):
        # Solo actualizamos si el valor es diferente al anterior para evitar bucles infinitos
        if st.session_state.lat_f != map_data['last_clicked']['lat']:
            st.session_state.lat_f = map_data['last_clicked']['lat']
            st.session_state.lon_f = map_data['last_clicked']['lng']
            st.rerun() # Esto obliga a que los campos de texto se actualicen al instante

    # Cuadro integrado de coordenadas (se llenará al instante gracias al rerun)
    col_a, col_b = st.columns(2)
    lat_input = col_a.text_input("Latitud capturada", value=st.session_state.lat_f, disabled=True)
    lon_input = col_b.text_input("Longitud capturada", value=st.session_state.lon_f, disabled=True)

    # --- NUEVA SECCIÓN: UBICACIÓN Y RECURSOS ---
    st.subheader("📍 Ubicación y Recursos")

    # Primera fila de ubicación
    col_loc1, col_loc2, col_loc3 = st.columns(3)
    with col_loc1:
        provincia = st.selectbox("PROVINCIA", ["SELECCIONAR", "BOCAS DEL TORO", "COCLE", "COLON", "CHIRIQUI", "DARIEN", "HERRERA", "LOS SANTOS", "VERAGUAS", "PANAMA", "PANAMA OESTE", "COMARCA EMBERA WOUNAAN", "COMARCA GUNA YALA", "COMARCA NASO TJER DI", "COMARCA NGABE BUGLE"])
    with col_loc2:
        distrito = st.selectbox("DISTRITO", ["SELECCIONAR", "AGUADULCE", "ALANJE", "ALMIRANTE", "ANTÓN", "ARRAIJÁN", "BALBOA", "BARÚ", "BESIKÓ", "BOCAS DEL TORO", "BOQUERÓN", "BOQUETE", "BUGABA", "CALOBRE", "CALOVÉBORA", "CAÑAZAS", "CAPIRA", "ATALAYA", "CÉMACO",
           "CHAGRES", "CHAME", "CHANGUINOLA", "CHEPIGANA", "CHEPO", "CHIMÁN", "CHIRIQUÍ GRANDE", "CHITRÉ", "COLÓN", "COMARCA GUNA YALA", "DAVID", "DOLEGA", "DONOSO", "GUALACA", "GUARARÉ", "JIRONDAI", "KANKINTÚ", 
           "KUSAPÍN", "LA CHORRERA", "LA MESA", "LA PINTADA", "LAS MINAS", "LAS PALMAS", "LAS TABLAS", "LOS POZOS", "LOS SANTOS", "MACARACAS", "MARIATO", "MIRONÓ", "MONTIJO", "MÜNA", "NATÁ", "NOLE DÜIMA", "ÑURÜM",
           "OCÚ", "OLÁ", "OMAR TORRIJOS HERRERA", "PANAMÁ", "PARITA", "PEDASÍ", "PENONOMÉ", "PESÉ", "PINOGANA", "POCRÍ", "PORTOBELO", "REMEDIOS", "RENACIMIENTO", "RÍO DE JESÚS", "SAMBÚ", "SAN CARLOS", "SAN FÉLIX",
           "SAN FRANCISCO", "SAN LORENZO", "SAN MIGUELITO", "SANTA CATALINA", "SANTA FE", "SANTA ISABEL", "SANTA MARÍA", "SANTIAGO", "SONÁ", "TABOGA", "TASO TJËR DI", "TIERRAS ALTAS", "TOLÉ", "TONOSÍ", "DON BOSCO",
          "CALIDONIA"])

    with col_loc3:
        corregimiento = st.selectbox("CORREGIMIENTO", ["SELECCIONAR", "24 DE DICIEMBRE", "ACHIOTE", "AGUA BUENA", "AGUA DE SALUD", "AGUA FRÍA", "AILIGANDÍ", "ALANJE", "ALCALDE DÍAZ", "ALMIRANTE", "ALTO BILINGÜE", "ALTO BOQUETE", "ALTO CABALLERO", "ALTO DE JESÚS",
              "ALTOS DE GÜERA", "AMADOR", "AMELIA DENIS DE ICAZA", "AGUADULCE", "ANCÓN", "ANTÓN", "ARENAS", "ARNULFO ARIAS", "AROSEMINA", "ARRAIJÁN", "ASERRÍO DE GARICHÉ", "ATALAYA", "BACO", "BÁGALA", "BAHÍA AZUL", 
              "BAHÍA HONDA", "BAJO BOQUETE", "BAJO CEDRO", "BAJO CORRAL", "BAJO CULUBRE", "BAJOS DE GÜERA", "BAKAMA", "BARNIZAL", "BARRANCO ADENTRO", "BARRIADA 4 DE ABRIL", "BARRIADA GUAYMÍ", "BARRIO BALBOA", 
              "BARRIO COLÓN", "CAÑAVERAL", "BARRIO FRANCÉS", "BARRIO NORTE", "BARRIO SUR", "BARRIOS UNIDOS", "BASTIMENTOS", "BAYANO", "BEJUCO", "BELISARIO FRÍAS", "BELISARIO PORRAS", "BELLA VISTA", "BETANIA", 
              "BIJAGUAL", "BISIRA", "BISVALLES", "BOCA CHICA", "BOCA DE BALSA", "BOCA DE CUPE", "BOCA DE TUCUÉ", "BOCA DEL DRAGO", "BOCA DEL MONTE", "BOCAS DEL TORO", "BONYIK", "BOQUERÓN", "BORÓ", "BREÑÓN", 
              "BRUJAS", "BUENA VISTA", "BUENOS AIRES", "BUGABA", "BURÍ", "BURUNGA", "CABALLERO", "CABUYA", "CACIQUE", "CAIMITILLO", "CAIMITO", "CALANTE", "CALDERA", "CALIDONIA", "CALOBRE", "CALOVÉBORA", 
              "CAMARÓN ARRIBA", "CAMBUTAL", "CAMOGANTÍ", "CAMPANA", "CANDELARIO OVALLE", "CANTA GALLO", "CANTO DEL LLANO", "CAÑAS", "CAÑAS GORDAS", "CAÑAVERAL", "CAÑAZAS", "CAÑITA", "CAPELLANÍA", "CAPIRA", 
              "CARLOS SANTANA ÁVILA", "CASCABEL", "CATIVÁ", "CATIVÉ", "CATORCE DE NOVIEMBRE", "CAUCHERO", "CÉBACO", "CEIBA", "CERMEÑO", "CERRO BANCO", "CERRO CAÑA", "CERRO DE CASA", "CERRO DE PLATA", 
              "CERRO IGLESIAS", "CERRO LARGO", "CERRO PATENA", "CERRO PELADO", "CERRO PUERCO", "CERRO PUNTA", "CERRO SILVESTRE", "CERRO VIEJO", "CHAME", "CHANGUINOLA", "CHEPIGANA", "CHEPILLO", "CHEPO", "CHICÁ", 
              "CHICHICA", "CHIGUIRÍ ARRIBA", "CHILIBRE", "CHIMÁN", "CHIRIQUÍ", "CHIRIQUÍ GRANDE", "CHITRA", "CHITRÉ", "CHUMICAL", "CHUPÁ", "CHUPAMPA", "CIRÍ DE LOS SOTOS", "CIRÍ GRANDE", "CIRICITO", "CIRILO GUAYNORA", 
              "COCHEA", "COCHIGRO", "COCLÉ", "COCLÉ DEL NORTE", "COLÓN CRISTÓBAL ESTE", "CORDILLERA", "COROZAL", "CORRAL FALSO", "COSTA HERMOSA", "CRISTÓBAL", "CRISTÓBAL ESTE", "CUANGO", "DOS RÍOS", "EDWIN FÁBREGA", 
              "EL ALTO", "EL ARADO", "EL AROMILLO", "EL BALE", "EL BARRERO", "EL BARRITO", "EL BEBEDERO", "EL BONGO", "EL CACAO", "EL CALABACITO", "EL CAÑAFÍSTULO", "EL CAÑO", "EL CAPURÍ", "EL CARATE", "EL CEDRO", 
              "EL CHIRÚ", "EL CHORRILLO", "EL CIRUELO", "EL COCAL", "EL COCLA", "EL COCO", "EL COPÉ", "EL CORTEZO", "EL CRISTO", "EL CUAY", "EL EJIDO", "EL EMPALME", "EL ESPINAL", "EL ESPINO", "EL GUABO", "EL GUÁSIMO", 
              "EL HARINO", "EL HATO", "EL HATO DE SAN JUAN DE DIOS", "EL HIGO", "EL LÍBANO", "EL LIMÓN", "EL LLANO", "EL MACANO", "EL MANANTIAL", "EL MARAÑÓN", "EL MARÍA", "EL MUÑOZ", "EL NANCITO", "EL PÁJARO", 
              "EL PALMAR", "EL PANTANO", "EL PAREDÓN", "EL PEDREGOSO", "EL PEÑÓN", "EL PICACHO", "EL PICADOR", "EL PIRO", "EL PIRO N°2", "EL PORVENIR", "EL POTRERO", "EL PRADO", "EL PUERTO", "EL REAL DE SANTA MARÍA", 
              "EL RETIRO", "EL RINCÓN", "EL ROBLE", "EL SESTEADERO", "EL SILENCIO", "EL TEJAR", "EL TERIBE", "EL TIJERA", "EL TORO", "EL VALLE", "EMPLANADA DE CHORCHA", "ENTRADERO DEL CASTILLO", "ERNESTO CÓRDOBA CAMPOS", 
              "ESCOBAL", "ESPINO AMARILLO", "FEUILLET", "FINCA 12", "FINCA 30", "FINCA 4", "FINCA 51", "FINCA 6", "FINCA 60", "FINCA 66", "FLORES", "GAIGIRGORDUB", "GARACHINÉ", "GARROTE", "GATUNCITO", "GOBEA", 
              "GOBERNADORA", "GÓMEZ", "GONZALO VÁSQUEZ", "GUABAL", "GUABITO", "GUACÁ", "GUADALUPE", "GUALACA", "GUÁNICO", "GUARARÉ", "GUARARÉ ARRIBA", "GUARIVIARA", "GUARUMAL", "GUAYABAL", "GUAYABITO", "GÜIBALE", 
              "GUORONÍ", "GUZMÁN", "HATO CHAMÍ", "HATO COROTÚ", "HATO CULANTRO", "HATO JOBO", "HATO JULÍ", "HATO PILÓN", "HERRERA", "HICACO", "HORCONCITOS", "HORNITO", "HURTADO", "ISLA DE CAÑAS", "ISLA GRANDE", 
              "ITURRALDE", "JÄDEBERI", "JAQUÉ", "JARAMILLO", "JINGURUDÓ", "JOSÉ DOMINGO ESPINAR", "JUAN DEMÓSTENES AROSEMENA", "JUAN DÍAZ", "JUAY", "JUSTO FIDEL PALACIOS", "KANKINTÚ", "KIKARI", "KRÜA", "KUSAPÍN", 
              "LA ARENA", "LA CARRILLO", "LA COLORADA", "LA CONCEPCIÓN", "LA ENCANTADA", "LA ENEA", "LA ENSENADA", "LA ERMITA", "LA ESMERALDA", "LA ESPIGADILLA", "LA ESTRELLA", "LA GARCEANA", "LA GLORIA", "LA GUINEA", 
              "LA LAGUNA", "LA LAJA", "LA MESA", "LA MIEL", "LA MONTAÑUELA", "LA PALMA", "LA PASERA", "LA PAVA", "LA PEÑA", "LA PINTADA", "LA PITALOZA", "LA RAYA DE CALOBRE", "LA RAYA DE SANTA MARÍA", "LA REPRESA", 
              "LA SOLEDAD", "LA TETILLA", "LA TIZA", "LA TRINCHERA", "LA TRINIDAD", "LA TRONOSA", "LA VILLA DE LOS SANTOS", "LA YEGUADA", "LAJAMINA", "LAJAS MINAS", "LAJAS ADENTRO", "LAJAS BLANCAS", "LAJAS DE TOLÉ", 
              "LAJERO", "LAS CABRAS", "LAS CRUCES", "LAS CUMBRES", "LAS DELICIAS", "LAS GARZAS", "LAS GUABAS", "LAS GUÍAS", "LAS HUACAS", "LAS LAJAS", "LAS LLANAS", "LAS LOMAS", "LAS MAÑANITAS", "LAS MARGARITAS", 
              "LAS MINAS", "LAS OLLAS ARRIBA", "LAS PALMAS", "LAS PALMITAS", "LAS TABLAS", "LAS TABLAS ABAJO", "LAS TRANCAS", "LAS UVAS", "LEONES", "LÍDICE", "LIMÓN", "LIMONES", "LLANO ABAJO", "LLANO BONITO", 
              "LLANO DE LA CRUZ", "LLANO DE PIEDRAS", "LLANO GRANDE", "LLANO LARGO", "LLANO NORTE", "LOLÁ", "LOMA YUCA", "LOS ALGARROBOS", "LOS ANASTACIOS", "LOS ÁNGELES", "LOS ASIENTOS", "LOS CANELOS", 
              "LOS CASTILLOS", "LOS CERRITOS", "LOS CERROS DE PAJA", "LOS DÍAZ", "LOS HATILLOS", "LOS LLANITOS", "LOS LLANOS", "LOS MILAGROS", "LOS NARANJOS", "LOS OLIVOS", "LOS POZOS", "LOS VALLES", "MACARACAS", 
              "MADUGANDÍ", "MAN CREEK", "MANACA", "MANUEL E. AMADOR TERRERO", "MANUEL ORTEGA", "MARACA", "MARÍA CHIQUITA", "MARIABÉ", "MARIATO", "MATEO ITURRALDE", "MENCHACA", "MENDOZA", "METETÍ", 
              "MIGUEL DE LA BORDA", "MIRAFLORES", "MIRAMAR", "MOGOLLÓN", "MONAGRILLO", "MONJARÁS", "MONTE LIRIO", "MONTIJO", "MREENI", "MÜNÜNÍ", "NÄMNONÍ", "NANCE DE RISCÓ", "NARGANÁ", "NATÁ", "NIBA", "NIBRA", 
              "NOMBRE DE DIOS", "NUARIO", "NUEVA CALIFORNIA", "NUEVA ESPERANZA", "NUEVA GORGONA", "NUEVA PROVIDENCIA", "NUEVO CHAGRES", "NUEVO EMPERADOR", "NUEVO MÉXICO", "NUEVO SANTIAGO", "OBALDÍA", "OCÚ", "OLÁ", 
              "OMAR TORRIJOS", "ORIA ARRIBA", "OTOQUE OCCIDENTE", "OTOQUE ORIENTE", "PACORA", "PAJA DE SOMBRERO", "PAJONAL", "PALENQUE", "PALMAS BELLAS", "PALMIRA", "PALO GRANDE", "PARAÍSO", "PARÍS", "PARITA", 
              "PARITILLA", "PARQUE LEFEVRE", "PÁSIGA", "PASO ANCHO", "PAYA", "PEDASÍ", "PEDREGAL", "PEDRO GONZÁLEZ", "PENONOMÉ", "PEÑA BLANCA", "PEÑAS CHATAS", "PERALES", "PESÉ", "PIEDRA ROJA", "PIEDRAS GORDAS", 
              "PILÓN", "PINOGANA", "PIÑA", "PIXVAE", "PLAYA CHIQUITA", "PLAYA LEONA", "PLAZA DE CAISÁN", "POCRÍ", "PONUGA", "PORTOBELILLO", "PORTOBELO", "POTRERILLOS", "POTRERILLOS ABAJO", "POTRERO DE CAÑA", 
              "POTUGA", "PROGRESO", "PÚCURO", "PUEBLO NUEVO", "PUEBLOS UNIDOS", "PUERTO ARMUELLES", "PUERTO CAIMITO", "PUERTO INDIO", "PUERTO OBALDÍA", "PUERTO PILÓN", "PUERTO PIÑA", "PUERTO VIDAL", "PUNTA CHAME", 
              "PUNTA LAUREL", "PUNTA PEÑA", "PUNTA ROBALO", "PURIO", "QUEBRADA DE LORO", "QUEBRADA DE ORO", "QUEBRADA DE PIEDRA", "QUEBRADA DEL ROSARIO", "QUEBRADA EL CIPRIÁN", "QUEBRO", "QUERÉVALO", "RAMBALA", 
              "REMANCE", "REMEDIOS", "RIECITO", "RINCÓN", "RINCÓN HONDO", "RÍO ABAJO", "RÍO CHIRIQUÍ", "RÍO CONGO", "RÍO CONGO ARRIBA", "RÍO DE JESÚS", "RÍO GRANDE", "RÍO HATO", "RÍO HONDO", "RÍO IGLESIAS", 
              "RÍO INDIO", "RÍO LUIS", "RÍO SABALO", "RÍO SERENO", "RODEO VIEJO", "RODOLFO AGUILAR DELGADO", "RODRIGO LUQUE", "ROKA", "ROVIRA", "RUBÉN CANTÚ", "RUFINA ALFARO", "SABANAGRANDE", "SABANITAS", "SABOGA", 
              "SAJALICES", "SALAMANCA", "SALTO DUPÍ", "SALUD", "SAMBOA", "SAMBÚ", "SAN ANDRÉS", "SAN ANTONIO", "SAN BARTOLO", "SAN CARLOS", "SAN CRISTÓBAL", "SAN FELIPE", "SAN FÉLIX", "SAN FRANCISCO", "SAN ISIDRO", 
              "SAN JOSÉ", "SAN JOSÉ DEL GENERAL", "SAN JUAN", "SAN JUAN BAUTISTA", "SAN JUAN DE DIOS", "SAN JUAN DE TURBE", "SAN LORENZO", "SAN MARCELO", "SAN MARTÍN", "SAN MARTÍN DE PORRES", "SAN MIGUEL", 
              "SAN PABLO NUEVO", "SAN PABLO VIEJO", "SAN PEDRITO", "SAN PEDRO DEL ESPINO", "SAN SAN DRUI", "SANTA ANA", "SANTA CATALINA", "SANTA CLARA", "SANTA CRUZ", "SANTA CRUZ DE CHININA", "SANTA FE", 
              "SANTA ISABEL", "SANTA LUCÍA", "SANTA MARÍA", "SANTA MARTA", "SANTA RITA", "SANTA ROSA", "SANTIAGO", "SANTIAGO ESTE", "SANTIAGO SUR", "SANTO DOMINGO", "SANTO TOMÁS", "SETEGANTÍ", "SIEYIC", 
              "SITIO PRADO", "SOLANO", "SOLOY", "SONÁ", "SORÁ", "SORTOVÁ", "SUSAMA", "TABOGA", "TAIMATÍ", "TEBARIO", "TIERRA OSCURA", "TIJERAS", "TINAJAS", "TOABRÉ", "TOBOBÉ", "TOCUMEN", "TOCUMEN", "TOLÉ", "TOLOTE", 
              "TONOSÍ", "TORTÍ", "TOZA", "TRES QUEBRADAS", "TUBUALÁ", "TUCUTÍ", "TULÚ", "TUWAI", "UMANÍ", "UNIÓN CHOCÓ", "UNIÓN DEL NORTE", "UNIÓN SANTEÑA", "URRACÁ", "UTIRA", "VACAMONTE", "VALLE BONITO", 
              "VALLE DE AGUAS ARRIBA", "VALLE DE RISCÓ", "VALLE RICO", "VALLERRIQUITO", "VELADERO", "VERACRUZ", "VICTORIANO LORENZO", "VIENTO FRÍO", "VIGUÍ", "VILLA CARMEN", "VILLA LOURDES", "VILLA ROSARIO", 
              "VILLARREAL", "VIRGEN DEL CARMEN", "VISTA ALEGRE", "VOLCÁN", "WARGANDÍ", "YAPE", "YAVIZA", "ZAPALLAL", "ZAPOTILLO"])
 

    # Segunda fila de detalles
    col_loc4, col_loc5, col_loc6 = st.columns(3)
    with col_loc4:
        referencia = st.text_input("REFERENCIA")
    with col_loc5:
        zp_policial = st.selectbox("ZP POLICIALES / ENLACE", ["SELECCIONAR", "FUERZA URBANA DE RÁPIDA INTERVENCIÓN - ALFA", "OPERACIONES DE TRÁNSITO", "SERVICIO DE POLICÍA DE NIÑEZ Y ADOLESCENCIA", "SERVICIO POLICIAL DE SEDES DIPLOMÁTICAS", 
             "SERVICIO POLICIAL DE SEGURIDAD PENITENCIARIA", "SERVICIO POLICIAL MOTORIZADO", "UNIDAD DE CONTROL DE MULTITUDES (U.C.M.)", "UNIDAD DE FUERZAS ESPECIALES", "UNIDAD POLICIAL DEL METRO (U.P.M.)", 
             "UNIDAD PREVENTIVA COMUNITARIA (U.P.C.)", "Z P - ARRAIJÁN", "Z P - BOCAS DEL TORO", "Z P - CANAL", "Z P - CHAME - CAPIRA - SAN CARLOS", "Z P - CHILIBRE", "Z P - CHIRIQUÍ", 
             "SERVICIO POLICIAL DE VIOLENCIA DOMÉSTICA Y DE GÉNERO", "Z P - COCLÉ", "Z P - COLÓN", "Z P - COMARCAL OCCIDENTAL", "Z P - DON BOSCO", "Z P - HERRERA", "Z P - LOS SANTOS", "Z P - NORTE", "Z P - OESTE", 
             "Z P - PACORA", "Z P - PANAMÁ OESTE", "Z P - RUFINA ALFARO", "Z P - SAN FRANCISCO", "Z P - SAN MIGUELITO", "Z P - VERAGUAS", "COORDINACIÓN CON ATTT", "COORDINACIÓN CON EMPRESA ELÉCTRICA", 
             "COORDINACIÓN CON EL MUNICIPIO PMA", "COORDINACIÓN CON LA POLICÍA AMBIENTAL", "COORDINACIÓN CON PERSONAL DE NATURGY", "COORDINACIÓN CON POLICIA MUNICIPAL", "COORDINACIÓN CON SENAN", 
             "COORDINACIÓN CON SINAPROC", "COORDINACIÓN CON SPI", "COORDINACIÓN CON UCM", "COORDINACIÓN CON BCBPM", "COORDINACIÓN CON POLICIA DE NIÑEZ Y ADOLENCIA", "DIIP", "DIJ", "SENAFRONT CARIBE", 
             "SENAFRONT OCCIDENTAL", "SENAFRONT ORIENTAL", "SENAFRONT PMÁ. ESTE"])
    with col_loc6:
        recursos = st.selectbox("RECURSOS", ["SELECCIONAR", "AMBULANCIA 911", "AMBULANCIA C. SALUD", "AMBULANCIA CSS", "AMBULANCIA SENAN", "AMBULANCIA SERV. PRIV.", "INSPECTOR DEL DNOT", "LANCHA RAPIDA", "LINCE PN", "LINCE SENAN", "MOTORIZADO DNOT", 
             "PATRULLA", "PATRULLA DNOT", "PATRULLA SENAN", "PATRULLERA", "RONDA A PIES", "RONDA A PIES SENAN", "INSPECTOR ATTT", "RONDA CICLISTA", "RONDA MOTOCICLISTA", "VEH. DE EXTINCIÓN", "VEH. EXPECIALISADOS", 
             "RONDA A PIES SENAFRONT", "PATRULLA SENAFRONT", "LINCE SENAFRONT", "AMBULANCIA SENAFRONT"])

    # --- FORMULARIO PARA DATOS DEL INCIDENTE ---
    with st.form("registro_maestro_total", clear_on_submit=True):
        st.subheader("⏱️ Tiempos, Unidades y Cámaras")
        c1, c2, c3, c4 = st.columns(4)
        with c1:
            fecha = st.date_input("FECHA")
            centro_mando = st.selectbox("CENTRO DE MANDO", ["SELECCIONAR", "CORCOL", "CON", "COMDA", "COMCH", "COMAR", "COMSAM", "COMCHEP", "CEVIBO"])
            unidad_VV = st.selectbox("UNIDAD DE VV/104", ["SELECCIONAR", "CABO 1RO ELMER RODRIGUEZ", "CABO 1RO ISMAEL PEÑA"])     
        with c2:
            canal = st.selectbox("CANAL DE ENTRADA", ["SELECCIONAR", "CLL-104", "VIDEO-VIGILANCIA", "RADIO FRECUENCIA", "OTRAS FUENTES", "BOTON DE PANICO", "ENLACE BMCBPMA", "ENLACE-DIP"])
            unidad_despacho = st.selectbox("UNIDAD DE DESPACHO", ["SELECCIONAR", "CABO 1RO ELMER RODRIGUEZ", "CABO 1RO ISMAEL PEÑA"])
        with c3:
            t_inicial = st.time_input("T. INICIAL")
            h_despacho = st.time_input("H. DESPACHO")
            camara_id = st.text_input("CAMARA/ID")
        with c4:
            h_atencion = st.time_input("H. ATENCION")
            h_cierre = st.time_input("H. CIERE")

        st.subheader("📋 Incidentes y Cierre")

        # --- LAS 2 LISTAS MAESTRAS DE OPCIONES ---
        # (Modifica las opciones aquí una sola vez y se aplicarán a ambos bloques)
        lista_tipos_maestra = ["SELECCIONAR", "Hurto de Vehículo", "Robo de Vehículo", "Accidente"]
        lista_subtipos_maestra = ["SELECCIONAR", "Opción 1", "Opción 2", "Opción 3", "Opción 4"]

        # --- 1. BLOQUE DE INCIDENTES ---
        c8, c9 = st.columns(2)
        with c8: 
            tipo_inc = st.selectbox("TIPO DE INCIDENTES", lista_tipos_maestra)
        with c9: 
            subtipo_inc = st.selectbox("SUBTIPO DE INCIDENTES", lista_subtipos_maestra)

        # --- 2. BLOQUE DE CIERRE (Usa exactamente las mismas listas) ---
        c_cierre1, c_cierre2 = st.columns(2)
        with c_cierre1:
            cierre_tipo = st.selectbox("CIERRE TIPO", lista_tipos_maestra)
        with c_cierre2:
            cierre_subtipo = st.selectbox("CIERRE SUBTIPO", lista_subtipos_maestra)
        # --- RESTO DE CAMPOS INTACTOS ---
        Narrativa = st.text_input("REPORTE/NARRATIVA")

        st.subheader("✅ Selección de Positivos")
        cols = st.columns(6)
        lista_positivos = ["SELECCIONAR", "APOYO A VEHICULO DE VALORES CON DESPERFECTOS", "APOYO AL CIUDADANO", "APOYO AL CIUDADANO BRINDAR SEGURIDAD A UNA PROSECION",
        "APOYO AL CIUDADANO CRUCE DE PEATÓN", "APOYO AL CIUDADANO PARA REPARAR VEHÍCULO", "APOYO AL CIUDADANO RESCATE DE PERSONA",
        "APREHENSIÓN DE MENOR POR ALERTA DE CUSTODIA", "ARMA DE FUEGO - DECOMISO - ESCOPETA", "ARMA DE FUEGO - DECOMISO - FUSIL",
        "ARMA DE FUEGO - DECOMISO - RIFLE", "ARMA DE FUEGO - DECOMISO - PISTOLA", "ARMA DE FUEGO - DECOMISO - REVOLVER",
        "ARMA DE FUEGO - HALLAZGO - ESCOPETA", "ARMA DE FUEGO - HALLAZGO - FUSIL", "ARMA DE FUEGO - HALLAZGO - PISTOLA",
        "ARMA DE FUEGO - HALLAZGO - REVOLVER", "ARMA DE FUEGO - REPLICA DECOMISO", "APOYO AL CIUDADANO RESCATE DE EMBARCACION",
        "ARMA DE FUEGO - REPLICA HALLAZGO", "ARTICULO DE DUDOSA PROCEDENCIA", "ARTICULO RECUPERADOS", "ATENCIÓN DE ATROPELLO",
        "ATENCIÓN DE ATROPELLO CON VICTIMA FATAL", "ATENCIÓN DE CAIDA DE VEHICULO EN LA CUNETA", "ATENCIÓN DE CHOQUE CON OBJETO FIJO",
        "ATENCIÓN DE COLISIÓN DE ALTO IMPACTO", "ATENCIÓN DE COLISIÓN MENOR", "ATENCIÓN DE COLISIÓN MULTIPLE",
        "ATENCIÓN DE COLISION Y FUGA", "ATENCIÓN DE COLISION Y VUELCO", "ATENCIÓN DE DERRAME DE COMBUSTIBLE",
        "ATENCIÓN DE DERRAPE DE MOTORIZADO", "ATENCIÓN DE DERRAPE DE MOTORIZADO CON VÍCTIMA FATAL", "ATENCIÓN DE TRIPLE COLISIÓN",
        "ATENCIÓN DE VUELCO", "ATENCIÓN PREHOSPITALARIA BCBPA", "ATENCIÓN PREHOSPITALARIA CSS", "ATENCIÓN PREHOSPITALARIA MINSACAPSI",
        "ATENCIÓN PREHOSPITALARIA PRIVADA", "ATENCIÓN PREHOSPITALARIA POLICÍA NACIONAL", "ATENCIÓN PREHOSPITALARIA SUME 911",
        "CIUDADANO CAPTURADO POR ALERTA PENITENCIARIA", "CIUDADANO APREHENDIDO", "CIUDADANO APREHENDIDO POR INVIOLABILIDAD DEL DOMICILIO",
        "CIUDADANO APREHENDIDO POR LIBERTAD VIGILADA", "CIUDADANO APREHENDIDO CON ACCESORIO DE ARMA DE FUEGO",
        "CIUDADANO APREHENDIDO POR SUPUESTA VINCULACIÓN A DELITO", "CIUDADANO APREHENDIDO POR SUBROGADO PENAL",
        "CIUDADANO APREHENDIDO POR PRIVACIÓN DE LIBERTAD", "CIUDADANO APREHENDIDO POR ESTAFA SIMPLE",
        "CIUDADANO APREHENDIDO POR INTENTO DE VIOLACIÓN", "CIUDADANO APREHENDIDO POR MALTRATO DE NIÑOS(AS)-ADOLESCENTES",
        "CIUDADANO APREHENDIDO POR AGRESIONES FISICAS", "CIUDADANO APREHENDIDO POR AGRESIONES VERBALES",
        "CIUDADANO APREHENDIDO POR QUEBRANTAMIENTO DE BOLETA DE PROTECCIÓN", "CIUDADANO APREHENDIDO POR LESIONES PERSONALES CON ARMA BLANCA",
        "CIUDADANO APREHENDIDO POR FALSIFICACIÓN DE DOCUMENTOS", "CIUDADANO APREHENDIDO POR FALSIFICACIÓN DE MONEDAS",
        "CIUDADANO APREHENDIDO POR NO PORTAR DOCUMENTO DE IDENTIDAD PERSONAL", "CIUDADANO APREHENDIDO POR DAÑO A LA PROP. PRIVADA",
        "CIUDADANO APREHENDIDO POR ALTERACIÓN DE LA CONVIVENCIA PACÍFICA", "CIUDADANO APREHENDIDO POR RIÑA O PELEA",
        "CIUDADANO APREHENDIDO POR CONSUMO DE LICOR EN VÍA PÚBLICA", "CIUDADANO APREHENDIDO POR VIOLENCIA DOMÉSTICA",
        "CIUDADANA APREHENDIDA POR VIOLENCIA DOMÉSTICA", "CIUDADANO APREHENDIDO CON SUSTANCIAS ILÍCITAS",
        "CIUDADANO APREHENDIDO POR LESIONES PERSONALES", "CIUDADANO APREHENDIDO POR OFICIO DE CAPTURA",
        "CIUDADANO APREHENDIDO POR OFICIO DE CONDUCCIÓN", "CIUDADANO APREHENDIDO POR HURTO A PROPIEDAD",
        "CIUDADANO APREHENDIDO POR HURTO", "CIUDADANO APREHENDIDO POR INTENTO DE HURTO",
        "CIUDADANO APREHENDIDO POR HURTO DE ACCESORIO DE VEHÍCULO", "CIUDADANO APREHENDIDO POR HURTO A LOCAL COMERCIAL",
        "CIUDADANO APREHENDIDO POR HURTO SIMPLE A PERSONA", "CIUDADANO APREHENDIDO POR HURTO SIMPLE A PROPIEDAD",
        "CIUDADANO APREHENDIDO POR HURTO A RESIDENCIA", "CIUDADANO APREHENDIDO POR HURTO DE VEHÍCULO",
        "CIUDADANO APREHENDIDO POR ROBO A PERSONA CON ARMA DE FUEGO", "CIUDADANO APREHENDIDO POR ROBO A PROPIEDAD",
        "CIUDADANO APREHENDIDO POR ROBO A LOCAL COMERCIAL", "CIUDADANO APREHENDIDO POR ROBO SIMPLE A PERSONA",
        "CIUDADANO APREHENDIDO POR ROBO SIMPLE (CARTERISTA)", "CIUDADANO APREHENDIDO POR ROBO DE VEHÍCULO (ALERTA TEMPRANA)",
        "CIUDADANO APREHENDIDO CON ARMA BLANCA", "CIUDADANO APREHENDIDO CON ARMA DE FUEGO",
        "CIUDADANO NOTIFICADO POR OFICIO DE CITACIÓN", "COORDINACIÓN CON ATENCIÓN PRIMARIA", "DECOMISO DE ARTICULOS PROHIBIDOS",
        "DECOMISO DE CAJETILLAS CIGARRILLOS", "HALLAZGO DE SUSTANCIA ILÍCITA", "DECOMISO DE SUSTANCIA ILÍCITA",
        "EXTINCIÓN DE INCENDIO", "EXTINCIÓN DEL CONATO DE INCENDIO", "INFRACCIÓN POR CEDER EL MANEJO A PERSONA NO AUTORIZADA",
        "INFRACCIÓN POR CONDUCIR A VELOCIDAD SUPERIOR AL LIMITE", "INFRACCIÓN POR CONDUCIR CON ALIENTO ALCOHÓLICO",
        "INFRACCIÓN POR CONDUCIR DE FORMA DESORDENADA", "INFRACCIÓN POR CONDUCTOR EN ESTADO DE EMBRIAGUEZ COMPROBADO",
        "INFRACCIÓN POR CONDUCTOR EN ESTADO ETILICO", "INFRACCIÓN POR EMITIR GASES, RUIDOS O SONIDOS EXCESIVOS",
        "INFRACCIÓN POR DAÑO A LA PROPIEDAD", "INFRACCIÓN POR DESATENDER LINEAS DE NO PARE, PASO PEATONAL E INDICACIONES",
        "INFRACCIÓN POR CONDUCIR POR EL CARRIL INDEBIDO", "INFRACCIÓN POR NEGARSE A HACERSE LA PRUEBA DE ALCOHOLEMIA",
        "INFRACCIÓN POR DESATENDER SEÑALES", "INFRACCIÓN POR HABLAR POR TELÉFONO CELULAR AL CONDUCIR",
        "INFRACCIÓN POR LICENCIA NO ADECUADA AL VEHICULO", "INFRACCIÓN POR LUCES INADECUADAS",
        "INFRACCIÓN NUNCA HA SACADO LICENCIA", "INFRACCIÓN POR NO PORTAR LICENCIA DE CONDUCIR",
        "INFRACCIÓN POR NO UTILIZAR EL CINTURÓN DE SEGURIDAD", "INFRACCIÓN POR PAPEL AHUMADO EN TONO O LUGAR NO AUTORIZADO",
        "INFRACCIÓN POR PASAR SEMÁFORO EN LUZ ROJA", "INFRACCIÓN POR POLIZA VENCIDA",
        "INFRACCIÓN POR PORTAR PLACA CON DISEÑO DIFERENTE A LA OFICIAL", "INFRACCIÓN POR PRESTAR EL SERVICIO EN RUTA DISTINTA A LA ESTABLECIDA",
        "INFRACCIÓN POR PRESTAR SERVICIO DE TRÁNSPORTE PÚBLICO EN VEHÍCULO NO AUTORIZADO", "INFRACCIÓN POR REALIZAR GIROS PROHIBIDOS",
        "INFRACCIÓN POR SIN CONDICIONES ADECUADAS DE SEGURIDAD", "INFRACCIÓN POR SIN EQUIPOS DE SEGURIDAD",
        "INFRACCIÓN POR CIRCULAR EN VÍA CONTRARIA", "INFRACCIÓN POR TRANSPORTAR EXESO DE PASAJERO",
        "INFRACCIÓN POR VEHÍCULOS DE TRANSPORTE PÚBLICO Y COMERCIAL SIN IDENTIFICACIÓN", "INFRACCIÓN POR VEHICULO CON LUCES NO ADECUADAS",
        "INFRACCIÓN POR VEHÍCULO SIN CINTA REFLECTIVA", "INFRACCIÓN POR VEHÍCULOS MAL ESTACIONADOS",
        "INFRACCIÓN POR REMOLCAR OTRO VEHÍCULO SIN LAS DEBIDAS MEDIDAS DE SEGURIDAD", "MENOR INFRACTOR POR HURTO",
        "MENOR INFRACTOR POR ROBO", "PROVEEDOR", "INFRACCIÓN POR LICENCIA DE CONDUCIR VENCIDA",
        "VEHÍCULO SOSPECHOSO", "RECUPERACIÓN DE MENOR EVADIDO", "REMOCIÓN DE VEHÍCULO EN GRÚA",
        "RESCATE DE ANIMAL DOMESTICO", "RESCATE DE MENOR POR ALERTA AMBER", "RESCATE DE MENOR POR RIEGO SOCIAL",
        "RESCATE DE PERSONA", "RESCATE DE VIDA Y FAUNA SILVESTRE", "RESTABLECIMIENTO DE LA SEGURIDA VÍAL",
        "RESTITUCIÓN DE PROPIEDAD EXTRAVIADA", "TRASLADO A HOSPITAL", "TRASLADO A HOSPITAL POR SUME 911",
        "TRASLADO A HOSPITAL POR BCBPA", "TRASLADO A HOSPITAL POR SERV. PRIVADO", "TRASLADO A HOSPITAL POR POLICÍA NACIONAL",
        "TRASLADO A HOSPITAL POR CSS", "VEHÍCULO RECUPERADO", "VEHÍCULO RECUPERADO POR SECUESTRO JUDICIAL DE BIENES",
        "VEHÍCULO RECUPERADO POR APROPIACIÓN INDEBIDA", "VEHÍCULO RECUPERADO POR HURTO (ALERTA TEMPRANA)",
        "VEHÍCULO RECUPERADO POR ROBO (ALERTA TEMPRANA)", "VEHÍCULO RECUPERADO POR OFICIO DE HURTO", "VEHÍCULO RECUPERADO POR OFICIO DE ROBO"]

        p1 = cols[0].selectbox("P1", lista_positivos, key="p1")
        p2 = cols[1].selectbox("P2", lista_positivos, key="p2")
        p3 = cols[2].selectbox("P3", lista_positivos, key="p3")
        p4 = cols[3].selectbox("P4", lista_positivos, key="p4")
        p5 = cols[4].selectbox("P5", lista_positivos, key="p5")
        p6 = cols[5].selectbox("P6", lista_positivos, key="p6")
        
        link_video = st.text_input("ENLACE DE VÍDEO")
        
        submitted = st.form_submit_button("Registrar Incidente Completo")
        
        if submitted:
            # Aquí es donde capturas lat_input y lon_input para guardar
            st.success(f"Incidente registrado en Lat: {st.session_state.lat_f}, Lon: {st.session_state.lon_f}")

    if st.sidebar.button("Cerrar Sesión"):
        st.session_state.autenticado = False
        st.rerun()